import { Plan, OnboardingSlide, Contact, Conversation, Message, UsageStats, ConnectivityState, ESIMCard } from '../types';

export const PLANS: Plan[] = [
  {
    id: 'basic',
    name: 'Starter',
    price: 0.99,
    currency: 'EUR',
    period: 'lună',
    features: [
      'Mesaje nelimitate',
      'Buton SOS de urgență',
      'GPS de bază',
      '5 GB date mobile',
      'Acoperire în 175 țări',
      'WiFi hotspot connect',
      '2 dispozitive',
    ],
    popular: false,
    dataLimit: '5 GB',
    messagingLimit: 'Nelimitate',
    trackingEnabled: false,
    sosEnabled: true,
  },
  {
    id: 'standard',
    name: 'Explorer',
    price: 2.99,
    currency: 'EUR',
    period: 'lună',
    features: [
      'Mesaje nelimitate',
      'Roaming global (175 țări)',
      'GPS tracking în timp real',
      'Buton SOS prioritar',
      '50 GB date mobile + roaming',
      'eSIM internațional inclus',
      '5 dispozitive',
      'Sincronizare automată',
      'Viteza 4G/5G',
    ],
    popular: true,
    dataLimit: '50 GB',
    messagingLimit: 'Nelimitate',
    trackingEnabled: true,
    sosEnabled: true,
  },
  {
    id: 'premium',
    name: 'Global Unlimited',
    price: 4.99,
    currency: 'EUR',
    period: 'lună',
    features: [
      'Mesaje nelimitate',
      'Internet NELIMITAT (fair use 200 GB)',
      'Satelit GPS global (orice loc)',
      'Roaming global complet (175+ țări)',
      'eSIM global inclus',
      'SOS satelit prioritar',
      'Dispozitive nelimitate',
      'WiFi + Cellular + Satelit auto-switch',
      'Viteza 5G prioritară',
      'Suport 24/7',
    ],
    popular: false,
    dataLimit: '200 GB',
    messagingLimit: 'Nelimitate',
    trackingEnabled: true,
    sosEnabled: true,
  },
];

export const ONBOARDING_SLIDES: OnboardingSlide[] = [
  {
    id: '1',
    title: 'Conectat Oriunde',
    description: 'Internet și comunicare în 175 de țări. WiFi, date mobile, roaming și satelit — totul într-o singură aplicație.',
    icon: 'satellite-variant',
  },
  {
    id: '2',
    title: 'Offline-First',
    description: 'Toate mesajele și locațiile se salvează local. Se sincronizează automat când apare conexiune, oriunde în lume.',
    icon: 'cloud-sync-outline',
  },
  {
    id: '3',
    title: 'SOS de Urgență',
    description: 'Trimite alerte de urgență cu locația ta exactă, chiar și fără internet. Siguranța ta e prioritatea noastră.',
    icon: 'alert-circle-outline',
  },
  {
    id: '4',
    title: 'Securitate Maximă',
    description: 'Mesajele sunt criptate end-to-end. Datele tale sunt protejate indiferent de tipul conexiunii.',
    icon: 'shield-lock-outline',
  },
];

export const MOCK_CONTACTS: Contact[] = [
  { id: '1', name: 'Maria Popescu', email: 'maria@example.com', isOnline: true, lastSeen: new Date().toISOString() },
  { id: '2', name: 'Andrei Ionescu', email: 'andrei@example.com', isOnline: false, lastSeen: '2026-03-17T15:30:00Z' },
  { id: '3', name: 'Elena Dumitrescu', email: 'elena@example.com', isOnline: true, lastSeen: new Date().toISOString() },
  { id: '4', name: 'Mihai Popa', email: 'mihai@example.com', isOnline: false, lastSeen: '2026-03-17T10:00:00Z' },
  { id: '5', name: 'Ana Stoica', email: 'ana@example.com', isOnline: false, lastSeen: '2026-03-16T20:00:00Z' },
  { id: '6', name: 'Echipa Salvare', email: 'rescue@satconnect.com', isOnline: true, lastSeen: new Date().toISOString() },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    participants: ['user', '1'],
    lastMessage: {
      id: 'msg-1',
      senderId: '1',
      receiverId: 'user',
      conversationId: 'conv-1',
      text: 'Am ajuns la tabăra de bază. Semnalul e slab dar funcționează!',
      timestamp: '2026-03-17T18:30:00Z',
      status: 'delivered',
      compressed: false,
      sizeBytes: 120,
    },
    unreadCount: 1,
    updatedAt: '2026-03-17T18:30:00Z',
  },
  {
    id: 'conv-2',
    participants: ['user', '2'],
    lastMessage: {
      id: 'msg-2',
      senderId: 'user',
      receiverId: '2',
      conversationId: 'conv-2',
      text: 'Locație trimisă via satelit.',
      timestamp: '2026-03-17T16:00:00Z',
      status: 'sent',
      compressed: true,
      sizeBytes: 45,
    },
    unreadCount: 0,
    updatedAt: '2026-03-17T16:00:00Z',
  },
  {
    id: 'conv-3',
    participants: ['user', '6'],
    lastMessage: {
      id: 'msg-3',
      senderId: '6',
      receiverId: 'user',
      conversationId: 'conv-3',
      text: 'Echipa de salvare a confirmat primirea alertei SOS.',
      timestamp: '2026-03-17T12:00:00Z',
      status: 'delivered',
      compressed: false,
      sizeBytes: 95,
    },
    unreadCount: 0,
    updatedAt: '2026-03-17T12:00:00Z',
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-10',
    senderId: 'user',
    receiverId: '1',
    conversationId: 'conv-1',
    text: 'Salut Maria! Sunt pe munte, semnalul e slab.',
    timestamp: '2026-03-17T17:00:00Z',
    status: 'delivered',
    compressed: false,
    sizeBytes: 80,
  },
  {
    id: 'msg-11',
    senderId: '1',
    receiverId: 'user',
    conversationId: 'conv-1',
    text: 'Ai grijă! Trimite-mi locația din când în când.',
    timestamp: '2026-03-17T17:05:00Z',
    status: 'delivered',
    compressed: false,
    sizeBytes: 85,
  },
  {
    id: 'msg-12',
    senderId: 'user',
    receiverId: '1',
    conversationId: 'conv-1',
    text: '📍 Locație partajată: 45.5943° N, 24.2737° E (Vârful Moldoveanu)',
    timestamp: '2026-03-17T18:00:00Z',
    status: 'sent',
    compressed: true,
    sizeBytes: 60,
  },
  {
    id: 'msg-13',
    senderId: '1',
    receiverId: 'user',
    conversationId: 'conv-1',
    text: 'Am ajuns la tabăra de bază. Semnalul e slab dar funcționează!',
    timestamp: '2026-03-17T18:30:00Z',
    status: 'delivered',
    compressed: false,
    sizeBytes: 120,
  },
];

export const MOCK_USAGE: UsageStats = {
  dataUsedMB: 127,
  dataLimitMB: 200,
  messagesSent: 342,
  messagesQueued: 3,
  locationsShared: 58,
  sosAlertsSent: 0,
  lastConnectionType: 'wifi',
  totalSyncEvents: 156,
  planDaysRemaining: 18,
};

export const MOCK_CONNECTIVITY: ConnectivityState = {
  isConnected: true,
  connectionType: 'wifi',
  signalStrength: 72,
  bandwidth: 2400,
  latency: 120,
  isSyncing: false,
  pendingSync: 3,
  lastSyncAt: '2026-03-17T19:00:00Z',
  activeESIM: '8940100000000000001',
  isRoaming: true,
  gpsEnabled: true,
  gpsAccuracy: 4.2,
};

export const CONNECTION_TYPE_LABELS: Record<string, string> = {
  wifi: 'WiFi',
  cellular: 'Date mobile',
  roaming: 'Roaming internațional',
  satellite: 'Satelit GPS',
  esim: 'eSIM activ',
  bluetooth: 'Bluetooth',
  none: 'Deconectat',
};

export const CONNECTION_TYPE_ICONS: Record<string, string> = {
  wifi: 'wifi',
  cellular: 'signal-cellular-3',
  roaming: 'earth',
  satellite: 'satellite-variant',
  esim: 'sim-outline',
  bluetooth: 'bluetooth',
  none: 'wifi-off',
};

export const MOCK_ESIM_CARDS: ESIMCard[] = [
  {
    id: 'esim-1',
    iccid: '8940100000000000001',
    label: 'Europa - 30+ țări',
    carrier: 'SatConnect EU',
    country: 'Europa (EU/EEA)',
    countryFlag: '🇪🇺',
    dataLimit: '10 GB',
    dataUsed: '3.2 GB',
    dataUsedMB: 3277,
    dataLimitMB: 10240,
    validUntil: '2026-04-17',
    status: 'active',
    isRoaming: true,
    planType: 'international',
    price: 9.99,
    currency: 'EUR',
  },
  {
    id: 'esim-2',
    iccid: '8940100000000000002',
    label: 'America & Asia - 100+ țări',
    carrier: 'SatConnect World',
    country: 'America, Asia, Africa (100+ țări)',
    countryFlag: '🌎',
    dataLimit: '5 GB',
    dataUsed: '1.1 GB',
    dataUsedMB: 1126,
    dataLimitMB: 5120,
    validUntil: '2026-04-17',
    status: 'active',
    isRoaming: true,
    planType: 'international',
    price: 14.99,
    currency: 'EUR',
  },
  {
    id: 'esim-3',
    iccid: '8940100000000000003',
    label: 'Global Total - 175 țări',
    carrier: 'SatConnect Global',
    country: 'Global (175 țări + satelit)',
    countryFlag: '🌍',
    dataLimit: '15 GB',
    dataUsed: '0 MB',
    dataUsedMB: 0,
    dataLimitMB: 15360,
    validUntil: '2026-04-17',
    status: 'inactive',
    isRoaming: true,
    planType: 'global',
    price: 24.99,
    currency: 'EUR',
  },
];
