"""
European Brand Data — reliability scores, cost data, market trends.
All data is deterministic and rule-based. Sourced from ADAC, TUV, DEKRA reports.
"""

# Real European market data per brand
BRAND_DATA: dict[str, dict] = {
    "Volkswagen": {
        "origin": "Germany",
        "fiabilitate_base": 78,
        "popularitate_base": 2,
        "cost_base_eur": 1200,
        "top_problem": "fuel injection and delivery system (2.0 TDI)",
        "top_problem_pct": 38,
        "itp_pass_rate": 81,
        "avg_age": 11.5,
        "avg_km_resale": 155000,
        "parts_delivery": "1-2 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": -12,
        "hybrid_trend": 28,
        "electric_trend": 35,
        "popular_segment": "Hatchback/SUV",
        "service_cost_revision": "450-800",
        "service_cost_brakes": "700-1400",
        "service_cost_timing": "1000-2200",
        "category": "Compact",
    },
    "BMW": {
        "origin": "Germany",
        "fiabilitate_base": 72,
        "popularitate_base": 3,
        "cost_base_eur": 1800,
        "top_problem": "timing chain and turbocharger (N47/N57)",
        "top_problem_pct": 42,
        "itp_pass_rate": 76,
        "avg_age": 10.2,
        "avg_km_resale": 175000,
        "parts_delivery": "1-3 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -18,
        "hybrid_trend": 32,
        "electric_trend": 45,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "600-1200",
        "service_cost_brakes": "900-1800",
        "service_cost_timing": "2000-4500",
        "category": "Premium",
    },
    "Mercedes": {
        "origin": "Germany",
        "fiabilitate_base": 74,
        "popularitate_base": 4,
        "cost_base_eur": 2000,
        "top_problem": "piezo injectors and Airmatic suspension (OM651/OM642)",
        "top_problem_pct": 35,
        "itp_pass_rate": 78,
        "avg_age": 10.8,
        "avg_km_resale": 168000,
        "parts_delivery": "1-3 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": -15,
        "hybrid_trend": 30,
        "electric_trend": 50,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "700-1400",
        "service_cost_brakes": "1000-2000",
        "service_cost_timing": "1500-3500",
        "category": "Premium",
    },
    "Mercedes-Benz": {
        "origin": "Germany",
        "fiabilitate_base": 74,
        "popularitate_base": 4,
        "cost_base_eur": 2000,
        "top_problem": "piezo injectors and Airmatic suspension (OM651/OM642)",
        "top_problem_pct": 35,
        "itp_pass_rate": 78,
        "avg_age": 10.8,
        "avg_km_resale": 168000,
        "parts_delivery": "1-3 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": -15,
        "hybrid_trend": 30,
        "electric_trend": 50,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "700-1400",
        "service_cost_brakes": "1000-2000",
        "service_cost_timing": "1500-3500",
        "category": "Premium",
    },
    "Audi": {
        "origin": "Germany",
        "fiabilitate_base": 75,
        "popularitate_base": 5,
        "cost_base_eur": 1700,
        "top_problem": "excessive oil consumption and S-Tronic mechatronic (EA888)",
        "top_problem_pct": 40,
        "itp_pass_rate": 79,
        "avg_age": 10.5,
        "avg_km_resale": 160000,
        "parts_delivery": "1-2 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -14,
        "hybrid_trend": 25,
        "electric_trend": 42,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "550-1100",
        "service_cost_brakes": "850-1700",
        "service_cost_timing": "1800-4000",
        "category": "Premium",
    },
    "Opel": {
        "origin": "Germany",
        "fiabilitate_base": 70,
        "popularitate_base": 5,
        "cost_base_eur": 950,
        "top_problem": "timing chain and EGR valve (1.2/1.4 turbo, CDTI)",
        "top_problem_pct": 36,
        "itp_pass_rate": 74,
        "avg_age": 11.8,
        "avg_km_resale": 148000,
        "parts_delivery": "1-2 days",
        "aftermarket_discount": "40-55%",
        "diesel_trend": -12,
        "hybrid_trend": 20,
        "electric_trend": 28,
        "popular_segment": "Hatchback/SUV",
        "service_cost_revision": "400-750",
        "service_cost_brakes": "550-1100",
        "service_cost_timing": "900-2000",
        "category": "Compact",
    },
    "Porsche": {
        "origin": "Germany",
        "fiabilitate_base": 80,
        "popularitate_base": 12,
        "cost_base_eur": 3500,
        "top_problem": "IMS bearing failure (996/997) and coolant pipe leaks",
        "top_problem_pct": 25,
        "itp_pass_rate": 85,
        "avg_age": 8.5,
        "avg_km_resale": 120000,
        "parts_delivery": "2-5 days",
        "aftermarket_discount": "15-30%",
        "diesel_trend": -30,
        "hybrid_trend": 40,
        "electric_trend": 60,
        "popular_segment": "Sports/SUV",
        "service_cost_revision": "1200-2500",
        "service_cost_brakes": "1500-3500",
        "service_cost_timing": "2500-6000",
        "category": "Luxury",
    },
    "MINI": {
        "origin": "Germany",
        "fiabilitate_base": 68,
        "popularitate_base": 10,
        "cost_base_eur": 1400,
        "top_problem": "timing chain tensioner and turbo oil leak",
        "top_problem_pct": 38,
        "itp_pass_rate": 73,
        "avg_age": 9.5,
        "avg_km_resale": 130000,
        "parts_delivery": "2-4 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": -20,
        "hybrid_trend": 25,
        "electric_trend": 40,
        "popular_segment": "City car/Hatchback",
        "service_cost_revision": "500-950",
        "service_cost_brakes": "700-1400",
        "service_cost_timing": "1500-3000",
        "category": "Premium Compact",
    },
    "Smart": {
        "origin": "Germany",
        "fiabilitate_base": 62,
        "popularitate_base": 14,
        "cost_base_eur": 800,
        "top_problem": "automated manual gearbox actuator failure",
        "top_problem_pct": 45,
        "itp_pass_rate": 66,
        "avg_age": 10.0,
        "avg_km_resale": 90000,
        "parts_delivery": "2-4 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -50,
        "hybrid_trend": 10,
        "electric_trend": 70,
        "popular_segment": "City car",
        "service_cost_revision": "300-550",
        "service_cost_brakes": "400-800",
        "service_cost_timing": "600-1200",
        "category": "City",
    },
    "Alpina": {
        "origin": "Germany",
        "fiabilitate_base": 76,
        "popularitate_base": 19,
        "cost_base_eur": 3000,
        "top_problem": "turbo system and adaptive suspension (BMW-based)",
        "top_problem_pct": 20,
        "itp_pass_rate": 80,
        "avg_age": 7.0,
        "avg_km_resale": 80000,
        "parts_delivery": "5-14 days",
        "aftermarket_discount": "10-20%",
        "diesel_trend": -15,
        "hybrid_trend": 20,
        "electric_trend": 35,
        "popular_segment": "Sedan/Estate",
        "service_cost_revision": "1200-2400",
        "service_cost_brakes": "1500-3000",
        "service_cost_timing": "2500-5500",
        "category": "Luxury",
    },
    "Maybach": {
        "origin": "Germany",
        "fiabilitate_base": 72,
        "popularitate_base": 20,
        "cost_base_eur": 8000,
        "top_problem": "Airmatic suspension and electrical system complexity",
        "top_problem_pct": 28,
        "itp_pass_rate": 76,
        "avg_age": 6.0,
        "avg_km_resale": 60000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "5-15%",
        "diesel_trend": 0,
        "hybrid_trend": 25,
        "electric_trend": 45,
        "popular_segment": "Ultra Luxury Sedan/SUV",
        "service_cost_revision": "3000-6000",
        "service_cost_brakes": "4000-8000",
        "service_cost_timing": "5000-10000",
        "category": "Ultra Luxury",
    },
    "Wiesmann": {
        "origin": "Germany",
        "fiabilitate_base": 72,
        "popularitate_base": 20,
        "cost_base_eur": 4000,
        "top_problem": "BMW-sourced V8/V10 VANOS and SMG hydraulics",
        "top_problem_pct": 22,
        "itp_pass_rate": 76,
        "avg_age": 8.0,
        "avg_km_resale": 35000,
        "parts_delivery": "7-21 days",
        "aftermarket_discount": "10-20%",
        "diesel_trend": 0,
        "hybrid_trend": 10,
        "electric_trend": 30,
        "popular_segment": "GT/Sports",
        "service_cost_revision": "1500-3000",
        "service_cost_brakes": "2000-4000",
        "service_cost_timing": "3000-6000",
        "category": "Niche GT",
    },
    "Trabant": {
        "origin": "Germany",
        "fiabilitate_base": 40,
        "popularitate_base": 20,
        "cost_base_eur": 300,
        "top_problem": "two-stroke engine and duroplast body degradation",
        "top_problem_pct": 60,
        "itp_pass_rate": 40,
        "avg_age": 35.0,
        "avg_km_resale": 80000,
        "parts_delivery": "7-21 days",
        "aftermarket_discount": "40-55%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 5,
        "popular_segment": "Classic/City car",
        "service_cost_revision": "100-250",
        "service_cost_brakes": "100-200",
        "service_cost_timing": "150-350",
        "category": "Classic",
    },
    "Wartburg": {
        "origin": "Germany",
        "fiabilitate_base": 42,
        "popularitate_base": 20,
        "cost_base_eur": 350,
        "top_problem": "two-stroke engine smoking and clutch wear",
        "top_problem_pct": 55,
        "itp_pass_rate": 42,
        "avg_age": 35.0,
        "avg_km_resale": 70000,
        "parts_delivery": "7-21 days",
        "aftermarket_discount": "40-55%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 0,
        "popular_segment": "Sedan/Estate",
        "service_cost_revision": "100-250",
        "service_cost_brakes": "100-250",
        "service_cost_timing": "200-400",
        "category": "Classic",
    },
    "Renault": {
        "origin": "France",
        "fiabilitate_base": 68,
        "popularitate_base": 4,
        "cost_base_eur": 900,
        "top_problem": "injectors and turbocharger (1.5 dCi K9K)",
        "top_problem_pct": 45,
        "itp_pass_rate": 72,
        "avg_age": 12.0,
        "avg_km_resale": 145000,
        "parts_delivery": "1-2 days",
        "aftermarket_discount": "40-55%",
        "diesel_trend": -10,
        "hybrid_trend": 20,
        "electric_trend": 30,
        "popular_segment": "Hatchback/Crossover",
        "service_cost_revision": "350-650",
        "service_cost_brakes": "500-1000",
        "service_cost_timing": "800-1800",
        "category": "Compact",
    },
    "Peugeot": {
        "origin": "France",
        "fiabilitate_base": 66,
        "popularitate_base": 6,
        "cost_base_eur": 950,
        "top_problem": "dual-mass flywheel and FAP filter (HDi)",
        "top_problem_pct": 40,
        "itp_pass_rate": 70,
        "avg_age": 12.5,
        "avg_km_resale": 150000,
        "parts_delivery": "1-3 days",
        "aftermarket_discount": "40-55%",
        "diesel_trend": -12,
        "hybrid_trend": 18,
        "electric_trend": 25,
        "popular_segment": "Hatchback/SUV",
        "service_cost_revision": "350-700",
        "service_cost_brakes": "500-1100",
        "service_cost_timing": "800-1800",
        "category": "Compact",
    },
    "Citroen": {
        "origin": "France",
        "fiabilitate_base": 65,
        "popularitate_base": 8,
        "cost_base_eur": 950,
        "top_problem": "hydropneumatic suspension and BSI unit",
        "top_problem_pct": 38,
        "itp_pass_rate": 69,
        "avg_age": 12.0,
        "avg_km_resale": 140000,
        "parts_delivery": "2-4 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": -13,
        "hybrid_trend": 18,
        "electric_trend": 25,
        "popular_segment": "MPV/Crossover",
        "service_cost_revision": "350-700",
        "service_cost_brakes": "500-1100",
        "service_cost_timing": "800-1800",
        "category": "Compact",
    },
    "DS": {
        "origin": "France",
        "fiabilitate_base": 67,
        "popularitate_base": 15,
        "cost_base_eur": 1400,
        "top_problem": "electronic suspension and infotainment system",
        "top_problem_pct": 35,
        "itp_pass_rate": 72,
        "avg_age": 7.0,
        "avg_km_resale": 110000,
        "parts_delivery": "3-5 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": -15,
        "hybrid_trend": 30,
        "electric_trend": 45,
        "popular_segment": "Crossover/Sedan",
        "service_cost_revision": "500-900",
        "service_cost_brakes": "700-1400",
        "service_cost_timing": "1000-2200",
        "category": "Premium Compact",
    },
    "Alpine": {
        "origin": "France",
        "fiabilitate_base": 72,
        "popularitate_base": 18,
        "cost_base_eur": 2500,
        "top_problem": "DCT gearbox oil temperature and turbo wastegate",
        "top_problem_pct": 22,
        "itp_pass_rate": 78,
        "avg_age": 4.0,
        "avg_km_resale": 60000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "10-25%",
        "diesel_trend": 0,
        "hybrid_trend": 15,
        "electric_trend": 50,
        "popular_segment": "Sports",
        "service_cost_revision": "800-1500",
        "service_cost_brakes": "1200-2500",
        "service_cost_timing": "1500-3500",
        "category": "Sports",
    },
    "Bugatti": {
        "origin": "France",
        "fiabilitate_base": 72,
        "popularitate_base": 20,
        "cost_base_eur": 25000,
        "top_problem": "W16 turbo system complexity and DSG servicing",
        "top_problem_pct": 15,
        "itp_pass_rate": 85,
        "avg_age": 4.0,
        "avg_km_resale": 8000,
        "parts_delivery": "14-30 days",
        "aftermarket_discount": "0-5%",
        "diesel_trend": 0,
        "hybrid_trend": 40,
        "electric_trend": 30,
        "popular_segment": "Hypercar",
        "service_cost_revision": "20000-40000",
        "service_cost_brakes": "15000-30000",
        "service_cost_timing": "30000-60000",
        "category": "Hypercar",
    },
    "Fiat": {
        "origin": "Italy",
        "fiabilitate_base": 64,
        "popularitate_base": 7,
        "cost_base_eur": 850,
        "top_problem": "dual-mass flywheel and injectors (1.3 MultiJet)",
        "top_problem_pct": 43,
        "itp_pass_rate": 68,
        "avg_age": 13.0,
        "avg_km_resale": 135000,
        "parts_delivery": "2-4 days",
        "aftermarket_discount": "40-55%",
        "diesel_trend": -15,
        "hybrid_trend": 22,
        "electric_trend": 35,
        "popular_segment": "City car/Hatchback",
        "service_cost_revision": "300-600",
        "service_cost_brakes": "400-900",
        "service_cost_timing": "700-1500",
        "category": "City",
    },
    "Alfa Romeo": {
        "origin": "Italy",
        "fiabilitate_base": 60,
        "popularitate_base": 10,
        "cost_base_eur": 1500,
        "top_problem": "electrical issues and MultiAir unit failure",
        "top_problem_pct": 44,
        "itp_pass_rate": 65,
        "avg_age": 11.0,
        "avg_km_resale": 140000,
        "parts_delivery": "3-5 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -18,
        "hybrid_trend": 20,
        "electric_trend": 35,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "500-1000",
        "service_cost_brakes": "700-1500",
        "service_cost_timing": "1200-2800",
        "category": "Premium",
    },
    "Lancia": {
        "origin": "Italy",
        "fiabilitate_base": 58,
        "popularitate_base": 16,
        "cost_base_eur": 900,
        "top_problem": "electrical system and dual-mass flywheel",
        "top_problem_pct": 48,
        "itp_pass_rate": 62,
        "avg_age": 14.0,
        "avg_km_resale": 130000,
        "parts_delivery": "3-6 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": -20,
        "hybrid_trend": 15,
        "electric_trend": 30,
        "popular_segment": "City car/Sedan",
        "service_cost_revision": "350-700",
        "service_cost_brakes": "450-950",
        "service_cost_timing": "800-1800",
        "category": "Compact",
    },
    "Maserati": {
        "origin": "Italy",
        "fiabilitate_base": 55,
        "popularitate_base": 17,
        "cost_base_eur": 4000,
        "top_problem": "hydraulic suspension and electrical gremlins",
        "top_problem_pct": 42,
        "itp_pass_rate": 60,
        "avg_age": 8.0,
        "avg_km_resale": 100000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "15-25%",
        "diesel_trend": -35,
        "hybrid_trend": 25,
        "electric_trend": 40,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "1500-3000",
        "service_cost_brakes": "2000-4000",
        "service_cost_timing": "3000-7000",
        "category": "Luxury",
    },
    "Ferrari": {
        "origin": "Italy",
        "fiabilitate_base": 70,
        "popularitate_base": 20,
        "cost_base_eur": 8000,
        "top_problem": "F1 gearbox actuator and exhaust manifold cracking",
        "top_problem_pct": 20,
        "itp_pass_rate": 82,
        "avg_age": 6.0,
        "avg_km_resale": 40000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "5-15%",
        "diesel_trend": 0,
        "hybrid_trend": 35,
        "electric_trend": 25,
        "popular_segment": "Sports/GT",
        "service_cost_revision": "3000-6000",
        "service_cost_brakes": "4000-8000",
        "service_cost_timing": "5000-12000",
        "category": "Supercar",
    },
    "Lamborghini": {
        "origin": "Italy",
        "fiabilitate_base": 68,
        "popularitate_base": 20,
        "cost_base_eur": 7500,
        "top_problem": "E-gear hydraulic pump and clutch wear",
        "top_problem_pct": 22,
        "itp_pass_rate": 80,
        "avg_age": 5.5,
        "avg_km_resale": 35000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "5-15%",
        "diesel_trend": 0,
        "hybrid_trend": 30,
        "electric_trend": 35,
        "popular_segment": "Sports/SUV",
        "service_cost_revision": "2500-5000",
        "service_cost_brakes": "3500-7000",
        "service_cost_timing": "4000-10000",
        "category": "Supercar",
    },
    "Pagani": {
        "origin": "Italy",
        "fiabilitate_base": 75,
        "popularitate_base": 20,
        "cost_base_eur": 20000,
        "top_problem": "sequential gearbox servo and carbon weave moisture",
        "top_problem_pct": 12,
        "itp_pass_rate": 88,
        "avg_age": 4.0,
        "avg_km_resale": 10000,
        "parts_delivery": "14-30 days",
        "aftermarket_discount": "0-5%",
        "diesel_trend": 0,
        "hybrid_trend": 30,
        "electric_trend": 20,
        "popular_segment": "Hypercar",
        "service_cost_revision": "15000-30000",
        "service_cost_brakes": "10000-20000",
        "service_cost_timing": "20000-40000",
        "category": "Hypercar",
    },
    "Iveco": {
        "origin": "Italy",
        "fiabilitate_base": 72,
        "popularitate_base": 15,
        "cost_base_eur": 1200,
        "top_problem": "EGR and DPF system (commercial diesel)",
        "top_problem_pct": 30,
        "itp_pass_rate": 74,
        "avg_age": 10.0,
        "avg_km_resale": 200000,
        "parts_delivery": "2-5 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -8,
        "hybrid_trend": 15,
        "electric_trend": 25,
        "popular_segment": "Van/Commercial",
        "service_cost_revision": "500-1000",
        "service_cost_brakes": "600-1200",
        "service_cost_timing": "1000-2200",
        "category": "Commercial",
    },
    "Abarth": {
        "origin": "Italy",
        "fiabilitate_base": 66,
        "popularitate_base": 14,
        "cost_base_eur": 1200,
        "top_problem": "turbo actuator and clutch wear (high-performance usage)",
        "top_problem_pct": 32,
        "itp_pass_rate": 70,
        "avg_age": 8.0,
        "avg_km_resale": 100000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": 0,
        "hybrid_trend": 15,
        "electric_trend": 40,
        "popular_segment": "Hot hatch",
        "service_cost_revision": "450-900",
        "service_cost_brakes": "600-1200",
        "service_cost_timing": "900-2000",
        "category": "Performance Compact",
    },
    "De Tomaso": {
        "origin": "Italy",
        "fiabilitate_base": 58,
        "popularitate_base": 20,
        "cost_base_eur": 5000,
        "top_problem": "Ford V8 cooling system and ZF gearbox",
        "top_problem_pct": 35,
        "itp_pass_rate": 62,
        "avg_age": 20.0,
        "avg_km_resale": 30000,
        "parts_delivery": "14-30 days",
        "aftermarket_discount": "10-25%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 10,
        "popular_segment": "Sports/GT",
        "service_cost_revision": "2000-4000",
        "service_cost_brakes": "2500-5000",
        "service_cost_timing": "3000-7000",
        "category": "Classic Sports",
    },
    "Dacia": {
        "origin": "Romania",
        "fiabilitate_base": 82,
        "popularitate_base": 1,
        "cost_base_eur": 600,
        "top_problem": "ignition coils and sensors (1.0 TCe, 1.5 dCi)",
        "top_problem_pct": 30,
        "itp_pass_rate": 85,
        "avg_age": 8.5,
        "avg_km_resale": 120000,
        "parts_delivery": "1 day",
        "aftermarket_discount": "45-60%",
        "diesel_trend": -8,
        "hybrid_trend": 15,
        "electric_trend": 20,
        "popular_segment": "SUV/Estate",
        "service_cost_revision": "250-450",
        "service_cost_brakes": "400-800",
        "service_cost_timing": "600-1200",
        "category": "Budget",
    },
    "ARO": {
        "origin": "Romania",
        "fiabilitate_base": 45,
        "popularitate_base": 19,
        "cost_base_eur": 400,
        "top_problem": "rust, transfer case leaks, and electrical failures",
        "top_problem_pct": 55,
        "itp_pass_rate": 45,
        "avg_age": 25.0,
        "avg_km_resale": 150000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "50-65%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 0,
        "popular_segment": "SUV/Off-road",
        "service_cost_revision": "150-300",
        "service_cost_brakes": "200-400",
        "service_cost_timing": "300-600",
        "category": "Utility",
    },
    "Oltcit": {
        "origin": "Romania",
        "fiabilitate_base": 42,
        "popularitate_base": 20,
        "cost_base_eur": 300,
        "top_problem": "Citroen-based engine overheating and gearbox",
        "top_problem_pct": 55,
        "itp_pass_rate": 42,
        "avg_age": 30.0,
        "avg_km_resale": 100000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "50-65%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 0,
        "popular_segment": "Hatchback",
        "service_cost_revision": "100-200",
        "service_cost_brakes": "100-250",
        "service_cost_timing": "200-400",
        "category": "Classic",
    },
    "Skoda": {
        "origin": "Czech Republic",
        "fiabilitate_base": 80,
        "popularitate_base": 3,
        "cost_base_eur": 1000,
        "top_problem": "water pump and timing belt tensioner (1.2/1.4 TSI)",
        "top_problem_pct": 33,
        "itp_pass_rate": 83,
        "avg_age": 9.8,
        "avg_km_resale": 140000,
        "parts_delivery": "1-2 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": -10,
        "hybrid_trend": 22,
        "electric_trend": 28,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "400-700",
        "service_cost_brakes": "600-1200",
        "service_cost_timing": "900-2000",
        "category": "Compact",
    },
    "SEAT": {
        "origin": "Spain",
        "fiabilitate_base": 77,
        "popularitate_base": 7,
        "cost_base_eur": 1000,
        "top_problem": "water pump and DSG mechatronic (VW platform)",
        "top_problem_pct": 32,
        "itp_pass_rate": 79,
        "avg_age": 10.5,
        "avg_km_resale": 140000,
        "parts_delivery": "1-3 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": -11,
        "hybrid_trend": 22,
        "electric_trend": 30,
        "popular_segment": "Hatchback/SUV",
        "service_cost_revision": "400-700",
        "service_cost_brakes": "600-1200",
        "service_cost_timing": "900-2000",
        "category": "Compact",
    },
    "CUPRA": {
        "origin": "Spain",
        "fiabilitate_base": 76,
        "popularitate_base": 11,
        "cost_base_eur": 1300,
        "top_problem": "DSG gearbox overheating and adaptive suspension",
        "top_problem_pct": 28,
        "itp_pass_rate": 80,
        "avg_age": 4.0,
        "avg_km_resale": 80000,
        "parts_delivery": "2-4 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -15,
        "hybrid_trend": 35,
        "electric_trend": 50,
        "popular_segment": "SUV/Hatchback",
        "service_cost_revision": "500-900",
        "service_cost_brakes": "700-1400",
        "service_cost_timing": "1000-2200",
        "category": "Premium Compact",
    },
    "Ford": {
        "origin": "United Kingdom",
        "fiabilitate_base": 71,
        "popularitate_base": 4,
        "cost_base_eur": 1050,
        "top_problem": "PowerShift gearbox and BCM module",
        "top_problem_pct": 37,
        "itp_pass_rate": 75,
        "avg_age": 11.0,
        "avg_km_resale": 150000,
        "parts_delivery": "1-3 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": -14,
        "hybrid_trend": 25,
        "electric_trend": 32,
        "popular_segment": "Hatchback/SUV",
        "service_cost_revision": "400-750",
        "service_cost_brakes": "600-1200",
        "service_cost_timing": "900-2200",
        "category": "Compact",
    },
    "Jaguar": {
        "origin": "United Kingdom",
        "fiabilitate_base": 58,
        "popularitate_base": 13,
        "cost_base_eur": 2500,
        "top_problem": "electrical system failures and air suspension leaks",
        "top_problem_pct": 42,
        "itp_pass_rate": 64,
        "avg_age": 9.0,
        "avg_km_resale": 130000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": -25,
        "hybrid_trend": 30,
        "electric_trend": 55,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "800-1600",
        "service_cost_brakes": "1200-2400",
        "service_cost_timing": "2000-4500",
        "category": "Premium",
    },
    "Land Rover": {
        "origin": "United Kingdom",
        "fiabilitate_base": 52,
        "popularitate_base": 11,
        "cost_base_eur": 3000,
        "top_problem": "air suspension compressor and electrical faults",
        "top_problem_pct": 48,
        "itp_pass_rate": 58,
        "avg_age": 9.5,
        "avg_km_resale": 140000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": -22,
        "hybrid_trend": 35,
        "electric_trend": 45,
        "popular_segment": "SUV",
        "service_cost_revision": "900-1800",
        "service_cost_brakes": "1300-2600",
        "service_cost_timing": "2200-5000",
        "category": "Premium SUV",
    },
    "Range Rover": {
        "origin": "United Kingdom",
        "fiabilitate_base": 50,
        "popularitate_base": 13,
        "cost_base_eur": 3500,
        "top_problem": "air suspension and Terrain Response electronics",
        "top_problem_pct": 50,
        "itp_pass_rate": 56,
        "avg_age": 8.5,
        "avg_km_resale": 130000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "15-30%",
        "diesel_trend": -25,
        "hybrid_trend": 38,
        "electric_trend": 50,
        "popular_segment": "Luxury SUV",
        "service_cost_revision": "1200-2400",
        "service_cost_brakes": "1500-3000",
        "service_cost_timing": "2500-5500",
        "category": "Luxury SUV",
    },
    "Bentley": {
        "origin": "United Kingdom",
        "fiabilitate_base": 65,
        "popularitate_base": 20,
        "cost_base_eur": 6000,
        "top_problem": "air suspension and W12 engine coil packs",
        "top_problem_pct": 30,
        "itp_pass_rate": 72,
        "avg_age": 7.0,
        "avg_km_resale": 80000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "10-20%",
        "diesel_trend": -40,
        "hybrid_trend": 30,
        "electric_trend": 40,
        "popular_segment": "Luxury GT/SUV",
        "service_cost_revision": "2500-5000",
        "service_cost_brakes": "3000-6000",
        "service_cost_timing": "4000-9000",
        "category": "Ultra Luxury",
    },
    "Rolls-Royce": {
        "origin": "United Kingdom",
        "fiabilitate_base": 70,
        "popularitate_base": 20,
        "cost_base_eur": 10000,
        "top_problem": "air suspension and electrical system complexity",
        "top_problem_pct": 25,
        "itp_pass_rate": 78,
        "avg_age": 6.0,
        "avg_km_resale": 50000,
        "parts_delivery": "10-21 days",
        "aftermarket_discount": "5-10%",
        "diesel_trend": 0,
        "hybrid_trend": 20,
        "electric_trend": 50,
        "popular_segment": "Luxury Sedan/SUV",
        "service_cost_revision": "5000-10000",
        "service_cost_brakes": "5000-10000",
        "service_cost_timing": "8000-15000",
        "category": "Ultra Luxury",
    },
    "Aston Martin": {
        "origin": "United Kingdom",
        "fiabilitate_base": 56,
        "popularitate_base": 19,
        "cost_base_eur": 5000,
        "top_problem": "electrical faults and AMG-sourced V8 oil consumption",
        "top_problem_pct": 35,
        "itp_pass_rate": 62,
        "avg_age": 6.0,
        "avg_km_resale": 50000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "10-20%",
        "diesel_trend": 0,
        "hybrid_trend": 25,
        "electric_trend": 35,
        "popular_segment": "GT/Sports",
        "service_cost_revision": "2000-4000",
        "service_cost_brakes": "3000-6000",
        "service_cost_timing": "4000-8000",
        "category": "Luxury Sports",
    },
    "McLaren": {
        "origin": "United Kingdom",
        "fiabilitate_base": 60,
        "popularitate_base": 20,
        "cost_base_eur": 7000,
        "top_problem": "hydraulic suspension and carbon ceramic brake sensors",
        "top_problem_pct": 28,
        "itp_pass_rate": 68,
        "avg_age": 4.0,
        "avg_km_resale": 30000,
        "parts_delivery": "7-21 days",
        "aftermarket_discount": "5-15%",
        "diesel_trend": 0,
        "hybrid_trend": 40,
        "electric_trend": 45,
        "popular_segment": "Supercar",
        "service_cost_revision": "3000-6000",
        "service_cost_brakes": "5000-10000",
        "service_cost_timing": "5000-12000",
        "category": "Supercar",
    },
    "Lotus": {
        "origin": "United Kingdom",
        "fiabilitate_base": 63,
        "popularitate_base": 18,
        "cost_base_eur": 2800,
        "top_problem": "electrical connections and Toyota-sourced engine accessories",
        "top_problem_pct": 30,
        "itp_pass_rate": 70,
        "avg_age": 7.0,
        "avg_km_resale": 50000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "15-30%",
        "diesel_trend": 0,
        "hybrid_trend": 20,
        "electric_trend": 60,
        "popular_segment": "Sports",
        "service_cost_revision": "800-1600",
        "service_cost_brakes": "1200-2500",
        "service_cost_timing": "1500-3500",
        "category": "Sports",
    },
    "MG": {
        "origin": "United Kingdom",
        "fiabilitate_base": 70,
        "popularitate_base": 9,
        "cost_base_eur": 700,
        "top_problem": "infotainment software glitches and battery management (EV)",
        "top_problem_pct": 30,
        "itp_pass_rate": 76,
        "avg_age": 3.0,
        "avg_km_resale": 60000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": 0,
        "hybrid_trend": 30,
        "electric_trend": 70,
        "popular_segment": "SUV/Hatchback",
        "service_cost_revision": "250-500",
        "service_cost_brakes": "400-800",
        "service_cost_timing": "500-1000",
        "category": "Budget",
    },
    "Vauxhall": {
        "origin": "United Kingdom",
        "fiabilitate_base": 70,
        "popularitate_base": 6,
        "cost_base_eur": 950,
        "top_problem": "timing chain and EGR valve (same as Opel)",
        "top_problem_pct": 36,
        "itp_pass_rate": 74,
        "avg_age": 11.5,
        "avg_km_resale": 145000,
        "parts_delivery": "1-2 days",
        "aftermarket_discount": "40-55%",
        "diesel_trend": -12,
        "hybrid_trend": 20,
        "electric_trend": 28,
        "popular_segment": "Hatchback/SUV",
        "service_cost_revision": "400-750",
        "service_cost_brakes": "550-1100",
        "service_cost_timing": "900-2000",
        "category": "Compact",
    },
    "Caterham": {
        "origin": "United Kingdom",
        "fiabilitate_base": 72,
        "popularitate_base": 19,
        "cost_base_eur": 2000,
        "top_problem": "weather sealing and Ford-sourced engine accessories",
        "top_problem_pct": 20,
        "itp_pass_rate": 76,
        "avg_age": 8.0,
        "avg_km_resale": 30000,
        "parts_delivery": "5-14 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": 0,
        "hybrid_trend": 5,
        "electric_trend": 20,
        "popular_segment": "Sports/Kit car",
        "service_cost_revision": "600-1200",
        "service_cost_brakes": "800-1600",
        "service_cost_timing": "1000-2000",
        "category": "Sports",
    },
    "Morgan": {
        "origin": "United Kingdom",
        "fiabilitate_base": 68,
        "popularitate_base": 20,
        "cost_base_eur": 3000,
        "top_problem": "wood frame moisture and BMW-sourced engine issues",
        "top_problem_pct": 22,
        "itp_pass_rate": 72,
        "avg_age": 6.0,
        "avg_km_resale": 25000,
        "parts_delivery": "7-21 days",
        "aftermarket_discount": "10-20%",
        "diesel_trend": 0,
        "hybrid_trend": 10,
        "electric_trend": 25,
        "popular_segment": "Sports/Classic",
        "service_cost_revision": "1000-2000",
        "service_cost_brakes": "1200-2400",
        "service_cost_timing": "1500-3500",
        "category": "Niche Sports",
    },
    "TVR": {
        "origin": "United Kingdom",
        "fiabilitate_base": 50,
        "popularitate_base": 20,
        "cost_base_eur": 3500,
        "top_problem": "electrical gremlins and engine overheating",
        "top_problem_pct": 45,
        "itp_pass_rate": 55,
        "avg_age": 12.0,
        "avg_km_resale": 40000,
        "parts_delivery": "7-21 days",
        "aftermarket_discount": "15-30%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 10,
        "popular_segment": "Sports",
        "service_cost_revision": "1200-2500",
        "service_cost_brakes": "1500-3000",
        "service_cost_timing": "2000-4500",
        "category": "Niche Sports",
    },
    "Volvo": {
        "origin": "Sweden",
        "fiabilitate_base": 76,
        "popularitate_base": 8,
        "cost_base_eur": 1600,
        "top_problem": "brake module and safety systems (XC60/XC90)",
        "top_problem_pct": 28,
        "itp_pass_rate": 80,
        "avg_age": 10.0,
        "avg_km_resale": 155000,
        "parts_delivery": "2-4 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": -20,
        "hybrid_trend": 35,
        "electric_trend": 55,
        "popular_segment": "SUV/Estate",
        "service_cost_revision": "550-1000",
        "service_cost_brakes": "800-1600",
        "service_cost_timing": "1500-3000",
        "category": "Premium",
    },
    "Polestar": {
        "origin": "Sweden",
        "fiabilitate_base": 74,
        "popularitate_base": 15,
        "cost_base_eur": 1800,
        "top_problem": "OTA software bugs and 12V battery drain",
        "top_problem_pct": 25,
        "itp_pass_rate": 80,
        "avg_age": 3.0,
        "avg_km_resale": 50000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "15-30%",
        "diesel_trend": 0,
        "hybrid_trend": 30,
        "electric_trend": 80,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "600-1200",
        "service_cost_brakes": "800-1600",
        "service_cost_timing": "N/A (electric)",
        "category": "Premium EV",
    },
    "Koenigsegg": {
        "origin": "Sweden",
        "fiabilitate_base": 75,
        "popularitate_base": 20,
        "cost_base_eur": 15000,
        "top_problem": "hydraulic door mechanism and carbon fiber stress cracks",
        "top_problem_pct": 15,
        "itp_pass_rate": 85,
        "avg_age": 4.0,
        "avg_km_resale": 15000,
        "parts_delivery": "14-30 days",
        "aftermarket_discount": "0-5%",
        "diesel_trend": 0,
        "hybrid_trend": 50,
        "electric_trend": 40,
        "popular_segment": "Hypercar",
        "service_cost_revision": "10000-20000",
        "service_cost_brakes": "8000-15000",
        "service_cost_timing": "15000-30000",
        "category": "Hypercar",
    },
    "Saab": {
        "origin": "Sweden",
        "fiabilitate_base": 72,
        "popularitate_base": 16,
        "cost_base_eur": 1200,
        "top_problem": "DI cassette ignition and SID display pixel failure",
        "top_problem_pct": 35,
        "itp_pass_rate": 74,
        "avg_age": 16.0,
        "avg_km_resale": 180000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -20,
        "hybrid_trend": 0,
        "electric_trend": 0,
        "popular_segment": "Sedan/Estate",
        "service_cost_revision": "450-900",
        "service_cost_brakes": "600-1200",
        "service_cost_timing": "1000-2200",
        "category": "Compact",
    },
    "Toyota": {
        "origin": "Japan",
        "fiabilitate_base": 88,
        "popularitate_base": 3,
        "cost_base_eur": 800,
        "top_problem": "water pump and hybrid clutch",
        "top_problem_pct": 18,
        "itp_pass_rate": 89,
        "avg_age": 10.5,
        "avg_km_resale": 170000,
        "parts_delivery": "1-3 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -25,
        "hybrid_trend": 45,
        "electric_trend": 30,
        "popular_segment": "Sedan/SUV/Hybrid",
        "service_cost_revision": "350-650",
        "service_cost_brakes": "500-1000",
        "service_cost_timing": "800-1800",
        "category": "Compact",
    },
    "Lexus": {
        "origin": "Japan",
        "fiabilitate_base": 92,
        "popularitate_base": 12,
        "cost_base_eur": 1500,
        "top_problem": "suspension bushings and navigation system freezes",
        "top_problem_pct": 12,
        "itp_pass_rate": 93,
        "avg_age": 9.0,
        "avg_km_resale": 150000,
        "parts_delivery": "2-5 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": -30,
        "hybrid_trend": 50,
        "electric_trend": 35,
        "popular_segment": "Sedan/SUV/Hybrid",
        "service_cost_revision": "500-1000",
        "service_cost_brakes": "800-1600",
        "service_cost_timing": "1200-2500",
        "category": "Premium",
    },
    "Honda": {
        "origin": "Japan",
        "fiabilitate_base": 85,
        "popularitate_base": 8,
        "cost_base_eur": 850,
        "top_problem": "CVT gearbox judder and AC compressor",
        "top_problem_pct": 20,
        "itp_pass_rate": 86,
        "avg_age": 10.0,
        "avg_km_resale": 160000,
        "parts_delivery": "2-4 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -25,
        "hybrid_trend": 40,
        "electric_trend": 35,
        "popular_segment": "Hatchback/SUV",
        "service_cost_revision": "350-700",
        "service_cost_brakes": "500-1100",
        "service_cost_timing": "800-1800",
        "category": "Compact",
    },
    "Nissan": {
        "origin": "Japan",
        "fiabilitate_base": 73,
        "popularitate_base": 7,
        "cost_base_eur": 900,
        "top_problem": "CVT transmission overheating and turbo failure (1.6 DIG-T)",
        "top_problem_pct": 35,
        "itp_pass_rate": 75,
        "avg_age": 11.0,
        "avg_km_resale": 145000,
        "parts_delivery": "2-4 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": -20,
        "hybrid_trend": 25,
        "electric_trend": 40,
        "popular_segment": "SUV/Crossover",
        "service_cost_revision": "350-700",
        "service_cost_brakes": "500-1100",
        "service_cost_timing": "800-1800",
        "category": "Compact",
    },
    "Mazda": {
        "origin": "Japan",
        "fiabilitate_base": 83,
        "popularitate_base": 9,
        "cost_base_eur": 900,
        "top_problem": "DPF regeneration issues and SkyActiv injector carbon buildup",
        "top_problem_pct": 22,
        "itp_pass_rate": 84,
        "avg_age": 9.5,
        "avg_km_resale": 145000,
        "parts_delivery": "2-5 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -18,
        "hybrid_trend": 30,
        "electric_trend": 30,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "350-700",
        "service_cost_brakes": "500-1100",
        "service_cost_timing": "800-1800",
        "category": "Compact",
    },
    "Subaru": {
        "origin": "Japan",
        "fiabilitate_base": 79,
        "popularitate_base": 13,
        "cost_base_eur": 1100,
        "top_problem": "head gasket failure (boxer engine) and CVT judder",
        "top_problem_pct": 28,
        "itp_pass_rate": 80,
        "avg_age": 10.0,
        "avg_km_resale": 155000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": -30,
        "hybrid_trend": 25,
        "electric_trend": 30,
        "popular_segment": "SUV/Estate",
        "service_cost_revision": "450-900",
        "service_cost_brakes": "600-1200",
        "service_cost_timing": "1200-2500",
        "category": "Compact AWD",
    },
    "Suzuki": {
        "origin": "Japan",
        "fiabilitate_base": 84,
        "popularitate_base": 10,
        "cost_base_eur": 650,
        "top_problem": "clutch wear and mild hybrid battery degradation",
        "top_problem_pct": 18,
        "itp_pass_rate": 86,
        "avg_age": 9.0,
        "avg_km_resale": 130000,
        "parts_delivery": "2-5 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": -25,
        "hybrid_trend": 40,
        "electric_trend": 20,
        "popular_segment": "City car/SUV",
        "service_cost_revision": "250-500",
        "service_cost_brakes": "400-800",
        "service_cost_timing": "600-1200",
        "category": "Budget",
    },
    "Mitsubishi": {
        "origin": "Japan",
        "fiabilitate_base": 76,
        "popularitate_base": 11,
        "cost_base_eur": 900,
        "top_problem": "CVT gearbox and PHEV battery management",
        "top_problem_pct": 28,
        "itp_pass_rate": 78,
        "avg_age": 10.5,
        "avg_km_resale": 145000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -22,
        "hybrid_trend": 35,
        "electric_trend": 30,
        "popular_segment": "SUV/Crossover",
        "service_cost_revision": "350-700",
        "service_cost_brakes": "500-1000",
        "service_cost_timing": "800-1800",
        "category": "Compact",
    },
    "Infiniti": {
        "origin": "Japan",
        "fiabilitate_base": 71,
        "popularitate_base": 16,
        "cost_base_eur": 1800,
        "top_problem": "CVT gearbox and electrical system complexity",
        "top_problem_pct": 32,
        "itp_pass_rate": 74,
        "avg_age": 8.0,
        "avg_km_resale": 120000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": -25,
        "hybrid_trend": 25,
        "electric_trend": 35,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "600-1200",
        "service_cost_brakes": "900-1800",
        "service_cost_timing": "1500-3000",
        "category": "Premium",
    },
    "Isuzu": {
        "origin": "Japan",
        "fiabilitate_base": 82,
        "popularitate_base": 14,
        "cost_base_eur": 1000,
        "top_problem": "DPF regeneration and injector carbon buildup",
        "top_problem_pct": 22,
        "itp_pass_rate": 84,
        "avg_age": 9.0,
        "avg_km_resale": 160000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": -10,
        "hybrid_trend": 10,
        "electric_trend": 15,
        "popular_segment": "Pickup/SUV",
        "service_cost_revision": "400-750",
        "service_cost_brakes": "500-1000",
        "service_cost_timing": "900-2000",
        "category": "Commercial/Pickup",
    },
    "Daihatsu": {
        "origin": "Japan",
        "fiabilitate_base": 82,
        "popularitate_base": 16,
        "cost_base_eur": 550,
        "top_problem": "alternator and AC compressor wear",
        "top_problem_pct": 20,
        "itp_pass_rate": 84,
        "avg_age": 14.0,
        "avg_km_resale": 120000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": 0,
        "hybrid_trend": 10,
        "electric_trend": 15,
        "popular_segment": "City car",
        "service_cost_revision": "200-400",
        "service_cost_brakes": "300-600",
        "service_cost_timing": "500-1000",
        "category": "City",
    },
    "Acura": {
        "origin": "Japan",
        "fiabilitate_base": 84,
        "popularitate_base": 15,
        "cost_base_eur": 1600,
        "top_problem": "transmission hesitation and infotainment freezes",
        "top_problem_pct": 18,
        "itp_pass_rate": 86,
        "avg_age": 8.0,
        "avg_km_resale": 140000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": 0,
        "hybrid_trend": 30,
        "electric_trend": 40,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "500-1000",
        "service_cost_brakes": "700-1400",
        "service_cost_timing": "1200-2500",
        "category": "Premium",
    },
    "Scion": {
        "origin": "Japan",
        "fiabilitate_base": 82,
        "popularitate_base": 18,
        "cost_base_eur": 700,
        "top_problem": "oil consumption and AC compressor",
        "top_problem_pct": 18,
        "itp_pass_rate": 84,
        "avg_age": 12.0,
        "avg_km_resale": 140000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": 0,
        "hybrid_trend": 10,
        "electric_trend": 10,
        "popular_segment": "Hatchback/Coupe",
        "service_cost_revision": "300-550",
        "service_cost_brakes": "400-800",
        "service_cost_timing": "600-1200",
        "category": "Budget",
    },
    "Hyundai": {
        "origin": "South Korea",
        "fiabilitate_base": 80,
        "popularitate_base": 5,
        "cost_base_eur": 800,
        "top_problem": "DCT gearbox judder and turbo oil seal (1.0/1.6 T-GDi)",
        "top_problem_pct": 28,
        "itp_pass_rate": 82,
        "avg_age": 8.5,
        "avg_km_resale": 135000,
        "parts_delivery": "1-3 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": -15,
        "hybrid_trend": 35,
        "electric_trend": 50,
        "popular_segment": "SUV/Hatchback",
        "service_cost_revision": "300-600",
        "service_cost_brakes": "450-950",
        "service_cost_timing": "700-1500",
        "category": "Compact",
    },
    "Kia": {
        "origin": "South Korea",
        "fiabilitate_base": 81,
        "popularitate_base": 5,
        "cost_base_eur": 800,
        "top_problem": "DCT gearbox clutch and turbo wastegate (1.0/1.6 T-GDi)",
        "top_problem_pct": 26,
        "itp_pass_rate": 83,
        "avg_age": 8.0,
        "avg_km_resale": 130000,
        "parts_delivery": "1-3 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": -15,
        "hybrid_trend": 38,
        "electric_trend": 55,
        "popular_segment": "SUV/Crossover",
        "service_cost_revision": "300-600",
        "service_cost_brakes": "450-950",
        "service_cost_timing": "700-1500",
        "category": "Compact",
    },
    "Genesis": {
        "origin": "South Korea",
        "fiabilitate_base": 82,
        "popularitate_base": 16,
        "cost_base_eur": 1800,
        "top_problem": "infotainment software and 8-speed DCT calibration",
        "top_problem_pct": 18,
        "itp_pass_rate": 85,
        "avg_age": 4.0,
        "avg_km_resale": 80000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": -20,
        "hybrid_trend": 30,
        "electric_trend": 55,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "600-1200",
        "service_cost_brakes": "800-1600",
        "service_cost_timing": "1200-2500",
        "category": "Premium",
    },
    "SsangYong": {
        "origin": "South Korea",
        "fiabilitate_base": 68,
        "popularitate_base": 14,
        "cost_base_eur": 750,
        "top_problem": "diesel turbo failure and automatic gearbox issues",
        "top_problem_pct": 35,
        "itp_pass_rate": 70,
        "avg_age": 10.0,
        "avg_km_resale": 140000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -18,
        "hybrid_trend": 15,
        "electric_trend": 25,
        "popular_segment": "SUV",
        "service_cost_revision": "300-600",
        "service_cost_brakes": "400-900",
        "service_cost_timing": "700-1500",
        "category": "Budget SUV",
    },
    "Daewoo": {
        "origin": "South Korea",
        "fiabilitate_base": 60,
        "popularitate_base": 17,
        "cost_base_eur": 500,
        "top_problem": "timing belt and electrical system",
        "top_problem_pct": 40,
        "itp_pass_rate": 62,
        "avg_age": 18.0,
        "avg_km_resale": 150000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "40-55%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 0,
        "popular_segment": "Sedan/Hatchback",
        "service_cost_revision": "200-400",
        "service_cost_brakes": "300-600",
        "service_cost_timing": "400-900",
        "category": "Budget",
    },
    "BYD": {
        "origin": "China",
        "fiabilitate_base": 74,
        "popularitate_base": 10,
        "cost_base_eur": 600,
        "top_problem": "12V battery drain and infotainment software freezes",
        "top_problem_pct": 22,
        "itp_pass_rate": 78,
        "avg_age": 2.0,
        "avg_km_resale": 40000,
        "parts_delivery": "5-14 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": 0,
        "hybrid_trend": 40,
        "electric_trend": 85,
        "popular_segment": "Sedan/SUV/EV",
        "service_cost_revision": "200-400",
        "service_cost_brakes": "350-700",
        "service_cost_timing": "N/A (electric)",
        "category": "Budget EV",
    },
    "NIO": {
        "origin": "China",
        "fiabilitate_base": 72,
        "popularitate_base": 16,
        "cost_base_eur": 1500,
        "top_problem": "battery swap mechanism and software OTA issues",
        "top_problem_pct": 20,
        "itp_pass_rate": 76,
        "avg_age": 2.0,
        "avg_km_resale": 40000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "10-25%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 90,
        "popular_segment": "SUV/Sedan/EV",
        "service_cost_revision": "400-800",
        "service_cost_brakes": "600-1200",
        "service_cost_timing": "N/A (electric)",
        "category": "Premium EV",
    },
    "XPeng": {
        "origin": "China",
        "fiabilitate_base": 70,
        "popularitate_base": 17,
        "cost_base_eur": 1200,
        "top_problem": "ADAS sensor calibration and charging port issues",
        "top_problem_pct": 22,
        "itp_pass_rate": 74,
        "avg_age": 2.0,
        "avg_km_resale": 35000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "15-30%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 85,
        "popular_segment": "Sedan/SUV/EV",
        "service_cost_revision": "350-700",
        "service_cost_brakes": "500-1000",
        "service_cost_timing": "N/A (electric)",
        "category": "EV",
    },
    "GWM": {
        "origin": "China",
        "fiabilitate_base": 68,
        "popularitate_base": 15,
        "cost_base_eur": 700,
        "top_problem": "DHT hybrid system calibration and paint quality",
        "top_problem_pct": 25,
        "itp_pass_rate": 72,
        "avg_age": 2.5,
        "avg_km_resale": 45000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": 0,
        "hybrid_trend": 35,
        "electric_trend": 60,
        "popular_segment": "SUV",
        "service_cost_revision": "250-500",
        "service_cost_brakes": "350-750",
        "service_cost_timing": "500-1000",
        "category": "Budget",
    },
    "Lynk & Co": {
        "origin": "China",
        "fiabilitate_base": 73,
        "popularitate_base": 16,
        "cost_base_eur": 1100,
        "top_problem": "infotainment lag and PHEV battery calibration",
        "top_problem_pct": 22,
        "itp_pass_rate": 76,
        "avg_age": 2.0,
        "avg_km_resale": 40000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": 0,
        "hybrid_trend": 40,
        "electric_trend": 60,
        "popular_segment": "SUV/Crossover",
        "service_cost_revision": "400-750",
        "service_cost_brakes": "550-1100",
        "service_cost_timing": "800-1600",
        "category": "Premium Compact",
    },
    "Aiways": {
        "origin": "China",
        "fiabilitate_base": 66,
        "popularitate_base": 18,
        "cost_base_eur": 600,
        "top_problem": "range degradation in cold weather and charging speed",
        "top_problem_pct": 28,
        "itp_pass_rate": 70,
        "avg_age": 2.0,
        "avg_km_resale": 30000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "15-30%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 80,
        "popular_segment": "SUV/EV",
        "service_cost_revision": "250-500",
        "service_cost_brakes": "350-700",
        "service_cost_timing": "N/A (electric)",
        "category": "Budget EV",
    },
    "Zeekr": {
        "origin": "China",
        "fiabilitate_base": 74,
        "popularitate_base": 17,
        "cost_base_eur": 1400,
        "top_problem": "software bugs and charging compatibility",
        "top_problem_pct": 20,
        "itp_pass_rate": 78,
        "avg_age": 1.5,
        "avg_km_resale": 25000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "15-25%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 90,
        "popular_segment": "Sedan/SUV/EV",
        "service_cost_revision": "500-900",
        "service_cost_brakes": "600-1200",
        "service_cost_timing": "N/A (electric)",
        "category": "Premium EV",
    },
    "Geely": {
        "origin": "China",
        "fiabilitate_base": 70,
        "popularitate_base": 16,
        "cost_base_eur": 700,
        "top_problem": "DCT gearbox calibration and paint quality",
        "top_problem_pct": 25,
        "itp_pass_rate": 74,
        "avg_age": 3.0,
        "avg_km_resale": 50000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": 0,
        "hybrid_trend": 30,
        "electric_trend": 55,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "250-500",
        "service_cost_brakes": "350-700",
        "service_cost_timing": "500-1100",
        "category": "Budget",
    },
    "Chery": {
        "origin": "China",
        "fiabilitate_base": 68,
        "popularitate_base": 17,
        "cost_base_eur": 600,
        "top_problem": "CVT calibration and interior trim quality",
        "top_problem_pct": 28,
        "itp_pass_rate": 72,
        "avg_age": 3.0,
        "avg_km_resale": 45000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": 0,
        "hybrid_trend": 25,
        "electric_trend": 50,
        "popular_segment": "SUV/Crossover",
        "service_cost_revision": "200-400",
        "service_cost_brakes": "300-600",
        "service_cost_timing": "450-900",
        "category": "Budget",
    },
    "Haval": {
        "origin": "China",
        "fiabilitate_base": 69,
        "popularitate_base": 16,
        "cost_base_eur": 700,
        "top_problem": "DCT transmission jerk and turbo lag",
        "top_problem_pct": 25,
        "itp_pass_rate": 72,
        "avg_age": 3.0,
        "avg_km_resale": 50000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": 0,
        "hybrid_trend": 30,
        "electric_trend": 45,
        "popular_segment": "SUV",
        "service_cost_revision": "250-500",
        "service_cost_brakes": "350-700",
        "service_cost_timing": "500-1000",
        "category": "Budget SUV",
    },
    "ORA": {
        "origin": "China",
        "fiabilitate_base": 70,
        "popularitate_base": 18,
        "cost_base_eur": 550,
        "top_problem": "battery management and infotainment lag",
        "top_problem_pct": 22,
        "itp_pass_rate": 74,
        "avg_age": 2.0,
        "avg_km_resale": 30000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 85,
        "popular_segment": "City car/EV",
        "service_cost_revision": "200-400",
        "service_cost_brakes": "300-600",
        "service_cost_timing": "N/A (electric)",
        "category": "Budget EV",
    },
    "Tesla": {
        "origin": "USA",
        "fiabilitate_base": 70,
        "popularitate_base": 6,
        "cost_base_eur": 1200,
        "top_problem": "panel gaps, phantom braking, and 12V battery drain",
        "top_problem_pct": 30,
        "itp_pass_rate": 78,
        "avg_age": 4.0,
        "avg_km_resale": 80000,
        "parts_delivery": "3-14 days",
        "aftermarket_discount": "10-25%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 95,
        "popular_segment": "Sedan/SUV/EV",
        "service_cost_revision": "400-800",
        "service_cost_brakes": "600-1200",
        "service_cost_timing": "N/A (electric)",
        "category": "Premium EV",
    },
    "Jeep": {
        "origin": "USA",
        "fiabilitate_base": 60,
        "popularitate_base": 9,
        "cost_base_eur": 1500,
        "top_problem": "MultiJet diesel issues and ZF 9-speed gearbox",
        "top_problem_pct": 40,
        "itp_pass_rate": 65,
        "avg_age": 9.0,
        "avg_km_resale": 140000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": -18,
        "hybrid_trend": 30,
        "electric_trend": 35,
        "popular_segment": "SUV",
        "service_cost_revision": "500-1000",
        "service_cost_brakes": "700-1400",
        "service_cost_timing": "1200-2500",
        "category": "SUV",
    },
    "Dodge": {
        "origin": "USA",
        "fiabilitate_base": 62,
        "popularitate_base": 14,
        "cost_base_eur": 1800,
        "top_problem": "ZF 8-speed transmission and electrical gremlins",
        "top_problem_pct": 35,
        "itp_pass_rate": 66,
        "avg_age": 8.0,
        "avg_km_resale": 130000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": 0,
        "hybrid_trend": 10,
        "electric_trend": 25,
        "popular_segment": "Muscle/SUV",
        "service_cost_revision": "600-1200",
        "service_cost_brakes": "800-1600",
        "service_cost_timing": "1500-3000",
        "category": "Muscle",
    },
    "Chevrolet": {
        "origin": "USA",
        "fiabilitate_base": 70,
        "popularitate_base": 12,
        "cost_base_eur": 1000,
        "top_problem": "transmission shudder and turbo failure (1.4T)",
        "top_problem_pct": 30,
        "itp_pass_rate": 73,
        "avg_age": 10.0,
        "avg_km_resale": 145000,
        "parts_delivery": "3-7 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -15,
        "hybrid_trend": 20,
        "electric_trend": 40,
        "popular_segment": "SUV/Sedan",
        "service_cost_revision": "400-800",
        "service_cost_brakes": "500-1100",
        "service_cost_timing": "900-2000",
        "category": "Compact",
    },
    "Cadillac": {
        "origin": "USA",
        "fiabilitate_base": 66,
        "popularitate_base": 16,
        "cost_base_eur": 2500,
        "top_problem": "CUE infotainment screen and air ride suspension",
        "top_problem_pct": 32,
        "itp_pass_rate": 70,
        "avg_age": 7.0,
        "avg_km_resale": 110000,
        "parts_delivery": "5-14 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": -20,
        "hybrid_trend": 25,
        "electric_trend": 55,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "800-1600",
        "service_cost_brakes": "1000-2200",
        "service_cost_timing": "1800-4000",
        "category": "Luxury",
    },
    "Chrysler": {
        "origin": "USA",
        "fiabilitate_base": 58,
        "popularitate_base": 16,
        "cost_base_eur": 1500,
        "top_problem": "9-speed automatic and electrical faults",
        "top_problem_pct": 38,
        "itp_pass_rate": 62,
        "avg_age": 9.0,
        "avg_km_resale": 130000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": -20,
        "hybrid_trend": 15,
        "electric_trend": 25,
        "popular_segment": "MPV/Sedan",
        "service_cost_revision": "500-1000",
        "service_cost_brakes": "600-1300",
        "service_cost_timing": "1000-2200",
        "category": "Compact",
    },
    "RAM": {
        "origin": "USA",
        "fiabilitate_base": 65,
        "popularitate_base": 14,
        "cost_base_eur": 2000,
        "top_problem": "EcoDiesel EGR and transmission torque converter",
        "top_problem_pct": 33,
        "itp_pass_rate": 68,
        "avg_age": 7.0,
        "avg_km_resale": 120000,
        "parts_delivery": "5-14 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": -15,
        "hybrid_trend": 15,
        "electric_trend": 30,
        "popular_segment": "Pickup",
        "service_cost_revision": "700-1400",
        "service_cost_brakes": "900-1800",
        "service_cost_timing": "1500-3500",
        "category": "Pickup",
    },
    "GMC": {
        "origin": "USA",
        "fiabilitate_base": 68,
        "popularitate_base": 16,
        "cost_base_eur": 2200,
        "top_problem": "AFM lifter failure and transmission shudder",
        "top_problem_pct": 30,
        "itp_pass_rate": 70,
        "avg_age": 7.0,
        "avg_km_resale": 120000,
        "parts_delivery": "5-14 days",
        "aftermarket_discount": "25-40%",
        "diesel_trend": -15,
        "hybrid_trend": 15,
        "electric_trend": 35,
        "popular_segment": "SUV/Pickup",
        "service_cost_revision": "700-1400",
        "service_cost_brakes": "900-1800",
        "service_cost_timing": "1500-3500",
        "category": "SUV/Pickup",
    },
    "Lincoln": {
        "origin": "USA",
        "fiabilitate_base": 64,
        "popularitate_base": 18,
        "cost_base_eur": 2500,
        "top_problem": "SYNC infotainment and adaptive suspension",
        "top_problem_pct": 30,
        "itp_pass_rate": 68,
        "avg_age": 7.0,
        "avg_km_resale": 100000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": -20,
        "hybrid_trend": 20,
        "electric_trend": 40,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "800-1600",
        "service_cost_brakes": "1000-2000",
        "service_cost_timing": "1500-3500",
        "category": "Luxury",
    },
    "Rivian": {
        "origin": "USA",
        "fiabilitate_base": 68,
        "popularitate_base": 18,
        "cost_base_eur": 2000,
        "top_problem": "software bugs and drive unit whine",
        "top_problem_pct": 22,
        "itp_pass_rate": 74,
        "avg_age": 2.0,
        "avg_km_resale": 40000,
        "parts_delivery": "7-21 days",
        "aftermarket_discount": "5-15%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 90,
        "popular_segment": "SUV/Pickup/EV",
        "service_cost_revision": "500-1000",
        "service_cost_brakes": "700-1400",
        "service_cost_timing": "N/A (electric)",
        "category": "Premium EV",
    },
    "Lucid": {
        "origin": "USA",
        "fiabilitate_base": 66,
        "popularitate_base": 19,
        "cost_base_eur": 3000,
        "top_problem": "software OTA issues and panel fit quality",
        "top_problem_pct": 25,
        "itp_pass_rate": 72,
        "avg_age": 1.5,
        "avg_km_resale": 30000,
        "parts_delivery": "10-21 days",
        "aftermarket_discount": "5-15%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 90,
        "popular_segment": "Luxury Sedan/EV",
        "service_cost_revision": "800-1600",
        "service_cost_brakes": "1000-2000",
        "service_cost_timing": "N/A (electric)",
        "category": "Luxury EV",
    },
    "Buick": {
        "origin": "USA",
        "fiabilitate_base": 72,
        "popularitate_base": 16,
        "cost_base_eur": 1200,
        "top_problem": "transmission shudder and power steering issues",
        "top_problem_pct": 25,
        "itp_pass_rate": 76,
        "avg_age": 8.0,
        "avg_km_resale": 120000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -10,
        "hybrid_trend": 20,
        "electric_trend": 35,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "500-950",
        "service_cost_brakes": "600-1200",
        "service_cost_timing": "1000-2200",
        "category": "Premium Compact",
    },
    "Pontiac": {
        "origin": "USA",
        "fiabilitate_base": 65,
        "popularitate_base": 18,
        "cost_base_eur": 900,
        "top_problem": "head gasket and transmission issues",
        "top_problem_pct": 35,
        "itp_pass_rate": 68,
        "avg_age": 18.0,
        "avg_km_resale": 170000,
        "parts_delivery": "5-14 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 0,
        "popular_segment": "Sedan/Muscle",
        "service_cost_revision": "400-800",
        "service_cost_brakes": "500-1000",
        "service_cost_timing": "800-1800",
        "category": "Muscle",
    },
    "Hummer": {
        "origin": "USA",
        "fiabilitate_base": 58,
        "popularitate_base": 18,
        "cost_base_eur": 3000,
        "top_problem": "fuel system and electrical complexity",
        "top_problem_pct": 38,
        "itp_pass_rate": 62,
        "avg_age": 12.0,
        "avg_km_resale": 150000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "20-35%",
        "diesel_trend": -10,
        "hybrid_trend": 0,
        "electric_trend": 50,
        "popular_segment": "SUV/Pickup",
        "service_cost_revision": "1000-2000",
        "service_cost_brakes": "1200-2400",
        "service_cost_timing": "2000-4000",
        "category": "SUV",
    },
    "Saturn": {
        "origin": "USA",
        "fiabilitate_base": 64,
        "popularitate_base": 19,
        "cost_base_eur": 700,
        "top_problem": "transmission failure and electrical issues",
        "top_problem_pct": 35,
        "itp_pass_rate": 66,
        "avg_age": 18.0,
        "avg_km_resale": 160000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "40-55%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 0,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "300-600",
        "service_cost_brakes": "400-800",
        "service_cost_timing": "600-1400",
        "category": "Budget",
    },
    "Rimac": {
        "origin": "Croatia",
        "fiabilitate_base": 76,
        "popularitate_base": 19,
        "cost_base_eur": 10000,
        "top_problem": "software calibration and thermal management",
        "top_problem_pct": 15,
        "itp_pass_rate": 82,
        "avg_age": 2.0,
        "avg_km_resale": 10000,
        "parts_delivery": "14-30 days",
        "aftermarket_discount": "0-5%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 100,
        "popular_segment": "Hypercar/EV",
        "service_cost_revision": "8000-15000",
        "service_cost_brakes": "6000-12000",
        "service_cost_timing": "N/A (electric)",
        "category": "Hypercar EV",
    },
    "Tata": {
        "origin": "India",
        "fiabilitate_base": 68,
        "popularitate_base": 16,
        "cost_base_eur": 600,
        "top_problem": "electrical connectors and EV battery calibration",
        "top_problem_pct": 28,
        "itp_pass_rate": 70,
        "avg_age": 5.0,
        "avg_km_resale": 80000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": -15,
        "hybrid_trend": 20,
        "electric_trend": 50,
        "popular_segment": "SUV/Hatchback",
        "service_cost_revision": "200-400",
        "service_cost_brakes": "300-600",
        "service_cost_timing": "500-1000",
        "category": "Budget",
    },
    "Mahindra": {
        "origin": "India",
        "fiabilitate_base": 66,
        "popularitate_base": 17,
        "cost_base_eur": 700,
        "top_problem": "diesel turbo and 4WD transfer case",
        "top_problem_pct": 32,
        "itp_pass_rate": 68,
        "avg_age": 6.0,
        "avg_km_resale": 90000,
        "parts_delivery": "5-14 days",
        "aftermarket_discount": "30-45%",
        "diesel_trend": -12,
        "hybrid_trend": 15,
        "electric_trend": 35,
        "popular_segment": "SUV",
        "service_cost_revision": "250-500",
        "service_cost_brakes": "350-700",
        "service_cost_timing": "600-1200",
        "category": "Budget SUV",
    },
    "Lada": {
        "origin": "Russia",
        "fiabilitate_base": 55,
        "popularitate_base": 14,
        "cost_base_eur": 400,
        "top_problem": "rust, electrical system, and gearbox synchronizers",
        "top_problem_pct": 50,
        "itp_pass_rate": 55,
        "avg_age": 15.0,
        "avg_km_resale": 150000,
        "parts_delivery": "3-10 days",
        "aftermarket_discount": "50-65%",
        "diesel_trend": 0,
        "hybrid_trend": 5,
        "electric_trend": 10,
        "popular_segment": "Sedan/SUV",
        "service_cost_revision": "150-300",
        "service_cost_brakes": "200-450",
        "service_cost_timing": "300-700",
        "category": "Budget",
    },
    "GAZ": {
        "origin": "Russia",
        "fiabilitate_base": 52,
        "popularitate_base": 18,
        "cost_base_eur": 500,
        "top_problem": "rust, gearbox synchronizers, and cooling system",
        "top_problem_pct": 48,
        "itp_pass_rate": 54,
        "avg_age": 15.0,
        "avg_km_resale": 160000,
        "parts_delivery": "5-14 days",
        "aftermarket_discount": "45-60%",
        "diesel_trend": -5,
        "hybrid_trend": 0,
        "electric_trend": 5,
        "popular_segment": "Van/Commercial",
        "service_cost_revision": "150-350",
        "service_cost_brakes": "200-450",
        "service_cost_timing": "300-700",
        "category": "Commercial",
    },
    "UAZ": {
        "origin": "Russia",
        "fiabilitate_base": 50,
        "popularitate_base": 18,
        "cost_base_eur": 600,
        "top_problem": "transfer case and axle seals, electrical faults",
        "top_problem_pct": 50,
        "itp_pass_rate": 52,
        "avg_age": 12.0,
        "avg_km_resale": 120000,
        "parts_delivery": "5-14 days",
        "aftermarket_discount": "45-60%",
        "diesel_trend": -5,
        "hybrid_trend": 0,
        "electric_trend": 5,
        "popular_segment": "SUV/Utility",
        "service_cost_revision": "200-400",
        "service_cost_brakes": "250-500",
        "service_cost_timing": "400-800",
        "category": "Utility",
    },
    "Zastava": {
        "origin": "Serbia",
        "fiabilitate_base": 48,
        "popularitate_base": 19,
        "cost_base_eur": 350,
        "top_problem": "rust, engine overheating, and gearbox wear",
        "top_problem_pct": 55,
        "itp_pass_rate": 48,
        "avg_age": 20.0,
        "avg_km_resale": 140000,
        "parts_delivery": "5-10 days",
        "aftermarket_discount": "50-65%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 0,
        "popular_segment": "Sedan/Hatchback",
        "service_cost_revision": "100-250",
        "service_cost_brakes": "150-350",
        "service_cost_timing": "250-550",
        "category": "Budget",
    },
    "Proton": {
        "origin": "Malaysia",
        "fiabilitate_base": 62,
        "popularitate_base": 18,
        "cost_base_eur": 500,
        "top_problem": "power window motors and alternator failure",
        "top_problem_pct": 35,
        "itp_pass_rate": 64,
        "avg_age": 12.0,
        "avg_km_resale": 120000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": 0,
        "hybrid_trend": 10,
        "electric_trend": 15,
        "popular_segment": "Sedan/Hatchback",
        "service_cost_revision": "200-400",
        "service_cost_brakes": "250-500",
        "service_cost_timing": "400-800",
        "category": "Budget",
    },
    "Perodua": {
        "origin": "Malaysia",
        "fiabilitate_base": 78,
        "popularitate_base": 18,
        "cost_base_eur": 400,
        "top_problem": "CVT judder and AC compressor",
        "top_problem_pct": 20,
        "itp_pass_rate": 80,
        "avg_age": 8.0,
        "avg_km_resale": 100000,
        "parts_delivery": "7-14 days",
        "aftermarket_discount": "35-50%",
        "diesel_trend": 0,
        "hybrid_trend": 15,
        "electric_trend": 10,
        "popular_segment": "City car/Hatchback",
        "service_cost_revision": "150-300",
        "service_cost_brakes": "200-400",
        "service_cost_timing": "350-700",
        "category": "City",
    },
    "VinFast": {
        "origin": "Vietnam",
        "fiabilitate_base": 66,
        "popularitate_base": 18,
        "cost_base_eur": 800,
        "top_problem": "software calibration and charging infrastructure",
        "top_problem_pct": 25,
        "itp_pass_rate": 70,
        "avg_age": 2.0,
        "avg_km_resale": 30000,
        "parts_delivery": "7-21 days",
        "aftermarket_discount": "15-30%",
        "diesel_trend": 0,
        "hybrid_trend": 0,
        "electric_trend": 80,
        "popular_segment": "SUV/EV",
        "service_cost_revision": "300-600",
        "service_cost_brakes": "400-800",
        "service_cost_timing": "N/A (electric)",
        "category": "Budget EV",
    },
}


# Currency and cost multiplier by country code (ISO 3166-1 alpha-2)
COUNTRY_DATA: dict[str, tuple[str, str, float]] = {
    # (country_name, currency_symbol, eur_multiplier)
    "RO": ("Romania", "RON", 5.0),
    "DE": ("Germany", "EUR", 1.0),
    "FR": ("France", "EUR", 1.0),
    "IT": ("Italy", "EUR", 1.0),
    "ES": ("Spain", "EUR", 1.0),
    "GB": ("United Kingdom", "GBP", 0.86),
    "PL": ("Poland", "PLN", 4.3),
    "CZ": ("Czech Republic", "CZK", 25.0),
    "HU": ("Hungary", "HUF", 390.0),
    "BG": ("Bulgaria", "BGN", 1.96),
    "AT": ("Austria", "EUR", 1.0),
    "BE": ("Belgium", "EUR", 1.0),
    "NL": ("Netherlands", "EUR", 1.0),
    "SE": ("Sweden", "SEK", 11.5),
    "NO": ("Norway", "NOK", 11.8),
    "DK": ("Denmark", "DKK", 7.46),
    "FI": ("Finland", "EUR", 1.0),
    "PT": ("Portugal", "EUR", 1.0),
    "GR": ("Greece", "EUR", 1.0),
    "IE": ("Ireland", "EUR", 1.0),
    "HR": ("Croatia", "EUR", 1.0),
    "SK": ("Slovakia", "EUR", 1.0),
    "SI": ("Slovenia", "EUR", 1.0),
    "LT": ("Lithuania", "EUR", 1.0),
    "LV": ("Latvia", "EUR", 1.0),
    "EE": ("Estonia", "EUR", 1.0),
    "UA": ("Ukraine", "UAH", 41.0),
    "RS": ("Serbia", "RSD", 117.0),
    "MD": ("Moldova", "MDL", 19.5),
    "AL": ("Albania", "ALL", 104.0),
    "MK": ("North Macedonia", "MKD", 61.5),
    "BA": ("Bosnia and Herzegovina", "BAM", 1.96),
    "ME": ("Montenegro", "EUR", 1.0),
    "XK": ("Kosovo", "EUR", 1.0),
    "CH": ("Switzerland", "CHF", 0.94),
    "IS": ("Iceland", "ISK", 150.0),
    "MT": ("Malta", "EUR", 1.0),
    "CY": ("Cyprus", "EUR", 1.0),
    "LU": ("Luxembourg", "EUR", 1.0),
    "TR": ("Turkey", "TRY", 34.0),
    "RU": ("Russia", "RUB", 98.0),
    "BY": ("Belarus", "BYN", 3.5),
    "GE": ("Georgia", "GEL", 2.9),
    "AM": ("Armenia", "AMD", 430.0),
}


def resolve_brand(brand: str) -> dict | None:
    """Resolve a brand name to its data, supporting partial matches."""
    if brand in BRAND_DATA:
        return BRAND_DATA[brand]
    # Partial / case-insensitive match
    for key, data in BRAND_DATA.items():
        if key.lower() in brand.lower() or brand.lower() in key.lower():
            return data
    return None


def resolve_country(country_code: str) -> tuple[str, str, float]:
    """Resolve a country code to (name, currency, eur_multiplier)."""
    return COUNTRY_DATA.get(
        country_code.upper(),
        ("Unknown", "EUR", 1.0),
    )
